import type { Metadata } from "next";
import Link from "next/link";
import {
  LegalEmailLink,
  LegalList,
  LegalNote,
  LegalPage,
  LegalSection,
} from "../components/legal";

export const metadata: Metadata = {
  title: "Terms of Service — Voom",
  description:
    "The terms for using Voom and MARA, its AI marketing manager — service description, connected accounts, your responsibilities, AI content review, billing, termination, and disclaimers.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      lead="These Terms of Service (Terms) govern your use of the Voom marketing platform, including the MARA AI marketing manager, the website, and all related features (together, the Service). By creating an account or using the Service you agree to these Terms."
    >
      <LegalSection title="The Service">
        <p>
          Voom is a marketing platform for small businesses. MARA, its AI
          marketing manager, helps plan marketing, draft content (such as
          Instagram captions, Reel concepts and scripts, emails, and SMS
          messages), build weekly content calendars, and report on results.
          The Service also includes contacts and audience management, campaign
          delivery by email and SMS where configured, Instagram account
          connection, and Reel production tools.
        </p>
        <LegalNote>
          Two current limitations, stated plainly: Voom does not currently
          publish to Instagram on your behalf — approvals in Voom approve
          drafts only. And billing is not live: the Service is currently free,
          the pricing screens are a demonstration, and no payment is taken.
        </LegalNote>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          You must be at least 16 years old to use the Service. You agree to
          provide accurate information for your account and business, to keep
          your login credentials secure, and to be responsible for activity
          under your account.
        </p>
      </LegalSection>

      <LegalSection title="Connected third-party accounts">
        <p>
          The Service lets you connect an Instagram account using Instagram
          OAuth. When you connect, you authorize that connection under
          Instagram and Meta terms, which apply to you independently of these
          Terms. You confirm you have the right to connect the account and to
          the content and data it contains. You can disconnect at any time from
          Connections, which removes the token Voom stores.
        </p>
      </LegalSection>

      <LegalSection title="Your responsibilities">
        <LegalList
          items={[
            "You are responsible for the business information you provide and for keeping it accurate.",
            "You must have the right to market to the contacts you add or import, including any consent required under the anti-spam, marketing, and data protection laws that apply to you, and for honoring opt-out requests from your contacts.",
            "You are responsible for the legality, accuracy, and non-infringement of the content you upload, generate, approve, and send.",
            "You must use the Service in compliance with all laws that apply to you and your business.",
          ]}
        />
      </LegalSection>

      <LegalSection title="AI content and human review">
        <p>
          Content MARA produces is generated by artificial intelligence and may
          contain errors, omissions, or inaccurate claims (including about your
          own business). Nothing is sent on your behalf without your explicit
          action: campaigns are only delivered when you approve and trigger the
          send, and drafts never leave the Service on their own. You are
          responsible for reviewing AI-generated content before approving or
          sending it, and for the final content you choose to send.
        </p>
      </LegalSection>

      <LegalSection title="No guaranteed marketing results">
        <p>
          Voom and MARA provide planning and drafting tools, not marketing
          outcomes. We do not guarantee any level of reach, engagement, leads,
          sales, or return on spend, and performance figures shown in the
          Service depend on factors outside our control, including your
          content, audience, channels, and market.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>You agree not to:</p>
        <LegalList
          items={[
            "use the Service for unlawful purposes or in violation of these Terms;",
            "send spam or unsolicited marketing, or add contacts without a lawful basis;",
            "upload content that infringes the rights of others, is defamatory, or is malicious;",
            "impersonate any person or business, or misrepresent your affiliation;",
            "attempt to probe, scan, attack, or disrupt the Service or its providers, to circumvent rate limits, or to gain unauthorized access to data;",
            "reverse engineer, scrape, resell, or build a competing product from the Service;",
            "introduce malware or harmful code, or interfere with other customers.",
          ]}
        />
      </LegalSection>

      <LegalSection title="Your content and licenses">
        <p>
          You keep ownership of your business content — the information,
          contacts, assets, and content you provide or approve. You grant Voom
          a limited license to host, process, and transmit that content solely
          to operate the Service for you, which includes sending it to the AI,
          email, SMS, and infrastructure providers described in our Privacy
          Policy. We do not train our own models on your content.
        </p>
      </LegalSection>

      <LegalSection title="Third-party services">
        <p>
          The Service depends on third-party providers, including Supabase,
          Vercel, Resend, ClickSend, Meta (Instagram), and AI providers. Their
          availability and their own terms are outside our control, and where
          they apply, those terms govern your use of their services. We are not
          responsible for acts or failures of these providers.
        </p>
      </LegalSection>

      <LegalSection title="Billing">
        <p>
          The Service is currently provided free of charge. If we introduce
          paid plans, we will present the pricing, what the plan includes, and
          any renewal and refund terms clearly before you commit, and any fees
          will be disclosed at the point of purchase. Prices may exclude taxes,
          which you are responsible for where applicable.
        </p>
      </LegalSection>

      <LegalSection title="Termination">
        <p>
          You may stop using the Service and ask us to delete your account data
          at any time — see the{" "}
          <Link
            href="/data-deletion"
            className="font-medium text-brand underline underline-offset-2 transition hover:decoration-2"
          >
            Data Deletion
          </Link>{" "}
          page. We may suspend or terminate access for breach of these Terms,
          for unlawful or abusive use, or if we discontinue a feature or the
          Service, and where reasonable we will tell you why. Sections that by
          their nature should survive (including disclaimers and liability
          limits) survive termination.
        </p>
      </LegalSection>

      <LegalSection title="Disclaimers">
        <p>
          The Service is provided as is and as available, and some features are
          early-stage and may change or be removed. To the maximum extent
          permitted by law, Voom disclaims all warranties, express or implied,
          including merchantability, fitness for a particular purpose, and
          non-infringement.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Voom will not be liable for
          indirect, incidental, special, or consequential damages, or for lost
          profits or revenue. Our aggregate liability for claims relating to
          the Service is limited to the greater of the amount you paid us in
          the twelve months before the claim or USD 100.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these Terms">
        <p>
          We may update these Terms as the Service evolves. The date at the top
          of this page shows when they were last updated, and material changes
          will be notified in the app or by email. Continuing to use the
          Service after a change means you accept the updated Terms.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these Terms? Email us at <LegalEmailLink />. You can
          also read our{" "}
          <Link
            href="/privacy"
            className="font-medium text-brand underline underline-offset-2 transition hover:decoration-2"
          >
            Privacy Policy
          </Link>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
