import "server-only";
import { normalizePlan, canUseAutomationMode } from "@/lib/billing/plans";

import { accountTimezone, formatLocalTime, isoToLocalDate, localDate, relativeDayLabel } from "@/lib/voom/timezone";
import { CADENCE_LABELS, DEFAULT_HORIZON_DAYS, isWithinHorizon, normalizeCadence, type Cadence } from "@/lib/voom/cadence";
import type { AdminClient } from "@/lib/post/server-data";
import { classifyReelProduction, type MaraProductionOption, type ReelProductionMethod } from "@/lib/mara/reel-production";
import {
  contentTypeLabel,
  deriveWorkflowStatus,
  failureStage,
  missedReason,
  WORKFLOW_STATUS_LABELS,
  type WorkflowStatus,
} from "./state";

/**
 * The single read model for the executable content workflow.
 *
 * Marketing Plan, Today, Approvals and Content Calendar all render THIS list.
 * Every row is one real `mara_drafts` workflow item joined to its real media,
 * calendar and publishing facts, so no screen can show content that does not
 * exist and no screen can disagree about a status or a date.
 *
 * Only the ACTIVE rolling workflow is surfaced. Rows produced by the legacy
 * ordinal-slot planner (`source_plan_item_key` = "0", "1", …) and any draft
 * whose slot lies outside the current rolling horizon stay in the database
 * untouched for history/debugging, but they are never mixed into the current
 * 7-day views. See `isCurrentWorkflowItem` for the exact validity rule — it is
 * based on current workflow validity (date-based slot + live horizon), never
 * on `created_at`, so a valid current-horizon item created before this change
 * remains fully visible.
 */

export interface WorkflowProductionView {
  /** MARA's recommended production method for this concept. */
  recommendedMethod: ReelProductionMethod | null;
  availableMethods: ReelProductionMethod[];
  selectedMethod: ReelProductionMethod | null;
  /** The resolved Create-with-MARA option — never silently absent. */
  maraOption: MaraProductionOption;
  /** Open `choose_reel_production` action id, when one exists. */
  actionId: string | null;
  /** Production status tracked on the open action ("produced", "video_generating", …). */
  productionStatus: string | null;
  shotInstructions: string[];
  allowedAssetKinds: ("image" | "video")[];
  missingAssetRequest: string | null;
  script: string | null;
}

export interface WorkflowView {
  draftId: string;
  calendarItemId: string | null;
  slotDate: string;
  contentType: "post" | "reel" | "story";
  contentTypeLabel: string;
  concept: string;
  caption: string;
  publishAt: string;
  /** Local date/time in the account timezone. */
  localDate: string;
  localTime: string;
  dayLabel: string;
  status: WorkflowStatus;
  statusLabel: string;
  failedStage: "media" | "publishing" | "rejected" | null;
  failureMessage: string | null;
  /** Truthful reason an approved item missed its schedule. Null unless missed. */
  missedReason: string | null;
  approvalActionId: string | null;
  hasMedia: boolean;
  instagramMediaId: string | null;
  /** Latest mara_media_generations status for this draft. */
  mediaStatus: string | null;
  /** Short-lived signed preview of the stored visual. Null until Voom owns bytes. */
  mediaPreviewUrl: string | null;
  /** "image" | "video" for the stored visual, when present. */
  mediaMimeType: string | null;
  /** True when the stored visual was generated by MARA (not uploaded). */
  mediaFromMara: boolean;
  /** Latest instagram_publish_queue row status for this draft. */
  queueStatus: string | null;
  /** Reel production facts (reels only). */
  production: WorkflowProductionView | null;
}

export interface WorkflowSnapshot {
  timeZone: string;
  today: string;
  cadence: Cadence;
  cadenceLabel: string;
  mode: "manual" | "assisted" | "autopilot";
  planId: string | null;
  planGoal: string | null;
  planValidFrom: string | null;
  planValidUntil: string | null;
  /** Every `mara_drafts` id attached to the active plan, including rows the horizon filter hides. */
  planDraftIds: string[];
  items: WorkflowView[];
}

export const EMPTY_SNAPSHOT: WorkflowSnapshot = {
  timeZone: "Asia/Dubai", today: "", cadence: "3x_week", cadenceLabel: CADENCE_LABELS["3x_week"],
  mode: "assisted", planId: null, planGoal: null, planValidFrom: null, planValidUntil: null, planDraftIds: [], items: [],
};

/** The new slot semantics: `source_plan_item_key` holds a real local date. */
const LOCAL_SLOT_DATE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * True when a draft uses the NEW date-based slot semantics — its per-plan slot
 * key is a real local YYYY-MM-DD date. Legacy ordinal keys ("0", "1", …) are
 * never current-workflow items, even when their publish time happens to fall
 * inside the live horizon.
 */
export function isLocalSlotDateKey(value: unknown): boolean {
  const key = String(value ?? "");
  if (!LOCAL_SLOT_DATE.test(key)) return false;
  const instant = Date.parse(`${key}T00:00:00Z`);
  // Round-trip guard: rejects impossible calendar dates the regex allows.
  return Number.isFinite(instant) && new Date(instant).toISOString().slice(0, 10) === key;
}

/** True when a draft carries a real, parseable proposed publish instant. */
export function isValidPublishInstant(value: unknown): boolean {
  return typeof value === "string" && value.length > 0 && Number.isFinite(Date.parse(value));
}

/** What the horizon rule needs from one workflow view. */
export type CurrentWorkflowItem = Pick<WorkflowView, "slotDate" | "localDate" | "status">;

/**
 * The one validity rule for surfacing a workflow item in the CURRENT views.
 *
 * An item is part of the active rolling workflow when it already uses the new
 * date-based slot (guaranteed by the row-level pre-filter) AND either
 *   - its slot/local publish date lies inside the current rolling horizon
 *     `[today, today + horizonDays)` in the account timezone, or
 *   - it has progressed beyond planning — approved and scheduled, published,
 *     or missed/failed — so legitimate scheduled, published and NEEDS
 *     ATTENTION work stays visible wherever its date now sits.
 *
 * Deliberately NOT part of the rule: `created_at`. A valid date-keyed item
 * inside the current horizon is never hidden just because it was created
 * before this change (or long ago); stale items are hidden because their slot
 * is legacy or outside the horizon.
 */
export function isCurrentWorkflowItem(item: CurrentWorkflowItem, selection: { today: string; horizonDays?: number }): boolean {
  const horizonDays = selection.horizonDays ?? DEFAULT_HORIZON_DAYS;
  if (isWithinHorizon(selection.today, item.slotDate, horizonDays)) return true;
  if (item.localDate && isWithinHorizon(selection.today, item.localDate, horizonDays)) return true;
  // Waiting-for-media, delayed-media and timed-out-media items are LIVE
  // scheduled work whose visual is not ready yet: if the owner rescheduled
  // them beyond the horizon they must stay visible (a held schedule is never
  // silently hidden), exactly like scheduled/published/missed/failed work.
  return (
    item.status === "scheduled" || item.status === "published" || item.status === "missed" || item.status === "failed"
    || item.status === "waiting_for_media" || item.status === "media_delayed" || item.status === "media_timed_out"
  );
}

/**
 * Filters an approval-action list (the Approvals screen feed) so rolling-plan
 * workflow cards follow the same horizon rule as the rest of the read model.
 *
 * Only cards that belong to the active plan's drafts are filtered: a stale
 * `propose_calendar_item` card for a legacy/out-of-horizon plan draft never
 * appears as a current approval need. Everything else — other tool names,
 * chat proposals without a draft, cards for drafts outside the active plan —
 * is passed through untouched.
 */
export function filterApprovalActionsForCurrentWorkflow<
  T extends { id: string | number; tool_name: string; new_value?: Record<string, unknown> | null; sanitized_arguments?: Record<string, unknown> | null },
>(actions: T[], snapshot: Pick<WorkflowSnapshot, "items" | "planDraftIds">): T[] {
  const surfacedActionIds = new Set(
    snapshot.items.flatMap((item) => (item.approvalActionId ? [item.approvalActionId] : [])),
  );
  const planDraftIds = new Set(snapshot.planDraftIds.map(String));
  return actions.filter((action) => {
    if (action.tool_name !== "propose_calendar_item") return true;
    const args = (action.new_value ?? action.sanitized_arguments ?? null) as { sourceDraftId?: unknown } | null;
    const sourceDraftId = args?.sourceDraftId;
    // Not a rolling-plan workflow card: never hidden by the horizon filter.
    if (typeof sourceDraftId !== "string" || !planDraftIds.has(sourceDraftId)) return true;
    return surfacedActionIds.has(String(action.id));
  });
}

/**
 * Loads the ONE executable workflow snapshot for the ACTIVE rolling horizon.
 *
 * Scoped to the active plan and resolved in the account's business timezone.
 * Of the plan's drafts, only current-workflow items are surfaced (see
 * `isCurrentWorkflowItem`): new date-keyed slots inside the live horizon, plus
 * scheduled/published/missed/failed work. Legacy ordinal-slot rows and
 * out-of-horizon drafts stay in the database, untouched, and simply never
 * reach the current views.
 */
export async function loadWorkflowSnapshot(
  admin: AdminClient, ownerId: string, options: { now?: Date; horizonDays?: number } = {},
): Promise<WorkflowSnapshot> {
  const now = options.now ?? new Date();
  const { data: business } = await admin.from("businesses")
    .select("content_frequency,automation_level,timezone,plan").eq("owner_user_id", ownerId).maybeSingle();
  const timeZone = accountTimezone((business as { timezone?: string | null } | null)?.timezone);
  const today = localDate(now, timeZone);
  const cadence = normalizeCadence(business?.content_frequency);
  
  const planId = normalizePlan((business as any)?.plan);
  let mode = business?.automation_level === "manual" || business?.automation_level === "autopilot"
    ? business.automation_level : "assisted";
  if (!canUseAutomationMode(planId, mode)) {
    mode = planId === "pro" ? "assisted" : "manual";
  }

  const { data: plan } = await admin.from("marketing_plans")
    .select("id,business_goal,valid_from,valid_until")
    .eq("owner_user_id", ownerId).eq("status", "active")
    .order("created_at", { ascending: false }).limit(1).maybeSingle();

  const snapshot: WorkflowSnapshot = {
    timeZone, today, cadence, cadenceLabel: CADENCE_LABELS[cadence], mode,
    planId: plan?.id ? String(plan.id) : null,
    planGoal: plan?.business_goal ? String(plan.business_goal) : null,
    planValidFrom: plan?.valid_from ? String(plan.valid_from) : null,
    planValidUntil: plan?.valid_until ? String(plan.valid_until) : null,
    planDraftIds: [],
    items: [],
  };
  if (!snapshot.planId) return snapshot;

  const { data: drafts } = await admin.from("mara_drafts")
    .select("id,kind,title,content,proposed_publish_at,status,source_plan_item_key")
    .eq("owner_user_id", ownerId).eq("source_plan_id", snapshot.planId)
    .order("proposed_publish_at", { ascending: true });

  // History stays in the database: every active-plan draft id is kept on the
  // snapshot (so the Approvals feed can recognise stale plan cards), while the
  // surfaced items below are narrowed to the current rolling workflow.
  const allRows = drafts ?? [];
  snapshot.planDraftIds = allRows.map((row) => String(row.id));
  if (!allRows.length) return snapshot;

  // Current-workflow rows only: the NEW date-based slot semantics plus a real
  // proposed publish instant. Legacy ordinal-slot rows are never surfaced, and
  // this is a read-model filter — no row is ever deleted or mutated here.
  const rows = allRows
    .filter((row) => isLocalSlotDateKey(row.source_plan_item_key) && isValidPublishInstant(row.proposed_publish_at));
  if (!rows.length) return snapshot;

  const ids = rows.map((row) => String(row.id));
  const [assets, generations, queue, calendar, approvals, productionActions] = await Promise.all([
    admin.from("post_draft_assets").select("draft_id,mime_type,origin,storage_path").eq("owner_user_id", ownerId).in("draft_id", ids),
    admin.from("mara_media_generations").select("draft_id,status,media_type,error_code,created_at,updated_at").eq("owner_user_id", ownerId).in("draft_id", ids).order("updated_at", { ascending: true }),
    admin.from("instagram_publish_queue").select("draft_id,status,instagram_media_id,failure_message,scheduled_at").eq("owner_user_id", ownerId).in("draft_id", ids),
    admin.from("content_calendar_items").select("id,source_draft_id").eq("owner_user_id", ownerId).in("source_draft_id", ids),
    admin.from("mara_pending_actions").select("id,sanitized_arguments,status")
      .eq("owner_user_id", ownerId).eq("tool_name", "propose_calendar_item").in("status", ["pending", "failed"]),
    admin.from("mara_pending_actions").select("id,new_value,sanitized_arguments,status,updated_at")
      .eq("owner_user_id", ownerId).eq("tool_name", "choose_reel_production").in("status", ["pending", "failed"])
      .order("updated_at", { ascending: true }),
  ]);

  const assetByDraft = new Map((assets.data ?? []).map((row) => [String(row.draft_id), row]));
  const mediaByDraft = new Map<string, { status: string; mediaType: string | null; errorCode: string | null; createdAt: string | null; updatedAt: string | null }>();
  for (const row of generations.data ?? []) {
    // Rows arrive oldest-first, so the newest generation wins. The timing and
    // reason columns are kept: the read model derives "Media generation
    // delayed" from updated_at and "Generation timed out" from the video job's
    // lifetime (created_at) or its terminal provider_timeout reason.
    mediaByDraft.set(String(row.draft_id), {
      status: String(row.status),
      mediaType: typeof row.media_type === "string" ? row.media_type : null,
      errorCode: typeof row.error_code === "string" ? row.error_code : null,
      createdAt: typeof row.created_at === "string" ? row.created_at : null,
      updatedAt: typeof row.updated_at === "string" ? row.updated_at : null,
    });
  }
  const publish = new Map((queue.data ?? []).map((row) => [String(row.draft_id), row]));
  const calendarIds = new Map((calendar.data ?? []).map((row) => [String(row.source_draft_id), String(row.id)]));
  const approvalIds = new Map<string, string>();
  for (const row of approvals.data ?? []) {
    const draftId = (row.sanitized_arguments as { sourceDraftId?: unknown } | null)?.sourceDraftId;
    if (typeof draftId === "string") approvalIds.set(draftId, String(row.id));
  }
  // The newest open reel-production action per draft carries its live state.
  interface ProductionActionRow { id: string; new_value?: Record<string, unknown> | null; sanitized_arguments?: Record<string, unknown> | null; status: string }
  const productionByDraft = new Map<string, ProductionActionRow>();
  for (const row of productionActions.data ?? []) {
    const value = (row.new_value ?? row.sanitized_arguments ?? null) as { draftId?: unknown } | null;
    const draftId = typeof value?.draftId === "string" ? value.draftId : null;
    if (draftId) productionByDraft.set(draftId, row);
  }

  snapshot.items = [];
  for (const row of rows) {
    const draftId = String(row.id);
    const publishRow = publish.get(draftId) as { status?: string; instagram_media_id?: string | null; failure_message?: string | null; scheduled_at?: string | null } | undefined;
    const kind = String(row.kind ?? "instagram_post");
    const contentType = kind === "reel" ? "reel" : kind === "story" ? "story" : "post";
    const publishAt = String(row.proposed_publish_at ?? "");
    const asset = assetByDraft.get(draftId) as { mime_type?: unknown; origin?: unknown; storage_path?: unknown } | undefined;
    const hasMedia = Boolean(asset && typeof asset.storage_path === "string");
    const media = mediaByDraft.get(draftId) ?? null;
    const facts = {
      draftStatus: (String(row.status ?? "draft") as "draft" | "approved" | "rejected"),
      hasMedia,
      mediaStatus: (media?.status ?? null) as never,
      mediaUpdatedAt: media?.updatedAt ?? null,
      mediaCreatedAt: media?.createdAt ?? null,
      mediaErrorCode: media?.errorCode ?? null,
      mediaType: media?.mediaType ?? null,
      publishStatus: publishRow?.status ?? null,
      awaitingApproval: approvalIds.has(draftId),
      publishAt,
      now,
    };
    const status = deriveWorkflowStatus(facts);

    let mediaPreviewUrl: string | null = null;
    if (hasMedia) {
      const { data: signed } = await admin.storage.from("mara-media")
        .createSignedUrl(String(asset!.storage_path), 600).catch(() => ({ data: null }) as { data: unknown });
      mediaPreviewUrl = (signed as { signedUrl?: string } | null)?.signedUrl ?? null;
    }

    const productionRow = productionByDraft.get(draftId) ?? null;
    const production = contentType === "reel" ? productionView(row, productionRow) : null;

    snapshot.items.push({
      draftId,
      calendarItemId: calendarIds.get(draftId) ?? null,
      slotDate: String(row.source_plan_item_key ?? (publishAt ? isoToLocalDate(publishAt, timeZone) : today)),
      contentType,
      contentTypeLabel: contentTypeLabel(contentType),
      concept: String(row.title ?? ""),
      caption: String(row.content ?? ""),
      publishAt,
      localDate: publishAt ? isoToLocalDate(publishAt, timeZone) : "",
      localTime: publishAt ? formatLocalTime(publishAt, timeZone) : "",
      dayLabel: publishAt ? relativeDayLabel(isoToLocalDate(publishAt, timeZone), now, timeZone) : "",
      status,
      statusLabel: WORKFLOW_STATUS_LABELS[status],
      failedStage: failureStage(facts),
      failureMessage: publishRow?.failure_message ?? null,
      missedReason: missedReason(facts),
      approvalActionId: approvalIds.get(draftId) ?? null,
      hasMedia,
      instagramMediaId: publishRow?.instagram_media_id ?? null,
      mediaStatus: media?.status ?? null,
      mediaPreviewUrl,
      mediaMimeType: hasMedia && typeof asset!.mime_type === "string" ? asset!.mime_type : null,
      mediaFromMara: asset?.origin === "mara",
      queueStatus: publishRow?.status ?? null,
      production,
    });
  }
  // The horizon rule (see `isCurrentWorkflowItem`): the ACTIVE rolling horizon
  // in the account's business timezone, plus work that has already progressed
  // to scheduled/published or needs attention (missed/failed). Legacy and
  // out-of-horizon rows are simply left out of the current views; they remain
  // stored, untouched, for history.
  snapshot.items = snapshot.items.filter((item) => isCurrentWorkflowItem(item, { today, horizonDays: options.horizonDays }));
  return snapshot;
}

/**
 * Reel production facts for one plan item: the open `choose_reel_production`
 * action's resolved capability when one exists, otherwise derived on the fly
 * from the concept. Either way the Create-with-MARA option is RESOLVED —
 * recommended, adapted, or truthfully disabled with a reason.
 */
function productionView(
  row: Record<string, unknown>,
  actionRow: { id: string; new_value?: Record<string, unknown> | null; sanitized_arguments?: Record<string, unknown> | null; status: string } | null,
): WorkflowProductionView {
  const concept = String(row.title ?? "");
  const script = String(row.content ?? "");
  const value = (actionRow?.new_value ?? actionRow?.sanitized_arguments ?? null) as Record<string, unknown> | null;

  const capability = classifyReelProduction({ concept, script });
  const storedOption = value?.maraOption as MaraProductionOption | null | undefined;
  const maraOption = storedOption && typeof storedOption.state === "string" ? storedOption : capability.maraOption;
  const storedRecommended = typeof value?.recommendedMethod === "string" ? value.recommendedMethod as ReelProductionMethod : null;
  let availableMethods: ReelProductionMethod[] = Array.isArray(value?.availableMethods)
    ? (value!.availableMethods as unknown[]).filter((method): method is ReelProductionMethod =>
      typeof method === "string" && ["create_with_mara", "film_yourself", "upload_asset"].includes(method))
    : capability.availableMethods;
  // Older capability payloads hid Create with MARA whenever filming was
  // recommended. The recommended method and the available methods are
  // DIFFERENT concepts: as long as MARA has a safe equivalent (direct or
  // adapted), the option must stay visible.
  if (maraOption.state !== "unavailable" && !availableMethods.includes("create_with_mara")) {
    availableMethods = ["create_with_mara", ...availableMethods];
  }

  return {
    recommendedMethod: storedRecommended ?? capability.recommendedMethod,
    availableMethods,
    selectedMethod: typeof value?.selectedProductionMethod === "string" ? value.selectedProductionMethod as ReelProductionMethod : null,
    maraOption,
    actionId: actionRow?.id ?? null,
    productionStatus: typeof value?.productionStatus === "string" ? value.productionStatus : null,
    shotInstructions: Array.isArray(value?.shotInstructions)
      ? (value!.shotInstructions as unknown[]).filter((shot): shot is string => typeof shot === "string")
      : capability.shotInstructions,
    allowedAssetKinds: Array.isArray(value?.allowedAssetKinds)
      ? (value!.allowedAssetKinds as unknown[]).filter((kind): kind is "image" | "video" => kind === "image" || kind === "video")
      : capability.allowedAssetKinds,
    missingAssetRequest: typeof value?.missingAssetRequest === "string" ? value.missingAssetRequest : capability.missingAssetRequest,
    script: value && typeof value.script === "string" ? value.script : script,
  };
}

/** Items whose local publish date is the real current local date. */
export function itemsForToday(snapshot: WorkflowSnapshot): WorkflowView[] {
  return snapshot.items.filter((item) => item.localDate === snapshot.today);
}

/** Operational counts for the Today command centre. */
export function todaySummary(snapshot: WorkflowSnapshot) {
  const items = snapshot.items;
  return {
    publishingToday: itemsForToday(snapshot).filter((item) => item.status !== "failed" && item.status !== "missed"),
    needsApproval: items.filter((item) => item.status === "needs_approval"),
    generating: items.filter((item) => item.status === "generating"),
    // Scheduled but CANNOT publish until the visual is ready — surfaced as its
    // own truthful bucket, never folded into "Scheduled". A timed-out
    // generation belongs here too: the queue row is still held in
    // 'waiting_for_media', and the item's own label says "Generation timed out".
    waitingForMedia: items.filter((item) => item.status === "waiting_for_media" || item.status === "media_delayed" || item.status === "media_timed_out"),
    failed: items.filter((item) => item.status === "failed"),
    missed: items.filter((item) => item.status === "missed"),
    scheduled: items.filter((item) => item.status === "scheduled"),
    published: items.filter((item) => item.status === "published"),
    next: items.find((item) => item.status === "scheduled" || item.status === "publishing") ?? null,
  };
}
