import "server-only";
import { normalizePlan, canUseAutomationMode } from "@/lib/billing/plans";

import { accountTimezone, formatLocalTime, isoToLocalDate, localDate, relativeDayLabel } from "@/lib/voom/timezone";
import { CADENCE_LABELS, DEFAULT_HORIZON_DAYS, isWithinHorizon, normalizeCadence, type Cadence } from "@/lib/voom/cadence";
import type { AdminClient } from "@/lib/post/server-data";
import { classifyReelProduction, type MaraProductionOption, type ReelProductionMethod } from "@/lib/mara/reel-production";
import {
  isValidChannelFormat,
  SOCIAL_CHANNEL_LABELS,
  SOCIAL_FORMAT_LABELS,
  type SocialFormat,
  type SocialMediaChannel,
} from "@/lib/social/channels";
import { tikTokQueueLabel } from "@/lib/social/server-drafts";
import { getTikTokQueueItemsForDrafts, type TikTokQueueRow } from "@/lib/tiktok/publish-queue";
import { getYouTubeQueueItemsForDrafts, type YouTubeQueueRow } from "@/lib/youtube/publish-queue";
import { youTubeQueueLabel } from "@/lib/social/server-drafts";
import { normalizeSelectedSocialChannels, parseWorkflowSlotIdentity, type PlannedContentType } from "./channel-planner";
import {
  contentTypeLabel,
  deriveWorkflowStatus,
  failureStage,
  missedReason,
  WORKFLOW_STATUS_LABELS,
  type WorkflowStatus,
} from "./state";

/**
 * The single read model for the executable content workflow.
 *
 * Marketing Plan, Today, Approvals and Content Calendar all render THIS list.
 * Every row is one real `mara_drafts` workflow item joined to its real media,
 * calendar and publishing facts, so no screen can show content that does not
 * exist and no screen can disagree about a status or a date.
 *
 * Only the ACTIVE rolling workflow is surfaced. Rows produced by the legacy
 * ordinal-slot planner (`source_plan_item_key` = "0", "1", …) and any draft
 * whose slot lies outside the current rolling horizon stay in the database
 * untouched for history/debugging, but they are never mixed into the current
 * 7-day views. See `isCurrentWorkflowItem` for the exact validity rule — it is
 * based on current workflow validity (date-based slot + live horizon), never
 * on `created_at`, so a valid current-horizon item created before this change
 * remains fully visible.
 */

export interface WorkflowProductionView {
  /** MARA's recommended production method for this concept. */
  recommendedMethod: ReelProductionMethod | null;
  availableMethods: ReelProductionMethod[];
  selectedMethod: ReelProductionMethod | null;
  /** The resolved Create-with-MARA option — never silently absent. */
  maraOption: MaraProductionOption;
  /** Open `choose_reel_production` action id, when one exists. */
  actionId: string | null;
  /** Production status tracked on the open action ("produced", "video_generating", …). */
  productionStatus: string | null;
  shotInstructions: string[];
  allowedAssetKinds: ("image" | "video")[];
  missingAssetRequest: string | null;
  script: string | null;
}

export interface WorkflowView {
  draftId: string;
  calendarItemId: string | null;
  slotDate: string;
  /** Actual immutable social assignment; never inferred as Instagram for unknown rows. */
  channel: SocialMediaChannel;
  format: SocialFormat;
  channelLabel: string;
  contentType: PlannedContentType;
  contentTypeLabel: string;
  sourceLabel: "Marketing Plan";
  sourcePlanId: string;
  sourcePlanItemKey: string;
  concept: string;
  caption: string;
  description: string | null;
  script: string[];
  publishAt: string;
  /** Local date/time in the account timezone. */
  localDate: string;
  localTime: string;
  dayLabel: string;
  status: WorkflowStatus;
  statusLabel: string;
  failedStage: "media" | "publishing" | "rejected" | null;
  failureMessage: string | null;
  /** Truthful reason an approved item missed its schedule. Null unless missed. */
  missedReason: string | null;
  approvalActionId: string | null;
  hasMedia: boolean;
  instagramMediaId: string | null;
  /** Latest mara_media_generations status for this draft. */
  mediaStatus: string | null;
  /** Short-lived signed preview of the stored visual. Null until Voom owns bytes. */
  mediaPreviewUrl: string | null;
  /** "image" | "video" for the stored visual, when present. */
  mediaMimeType: string | null;
  /** True when the stored visual was generated by MARA (not uploaded). */
  mediaFromMara: boolean;
  /** Latest durable channel queue status for this draft, if any. */
  queueStatus: string | null;
  /** Safe metadata from the private stored asset; never exposes its storage path. */
  mediaDisplayName: string | null;
  /** Reel production facts (Instagram Reels only). */
  production: WorkflowProductionView | null;
}

export interface WorkflowSnapshot {
  timeZone: string;
  today: string;
  cadence: Cadence;
  cadenceLabel: string;
  mode: "manual" | "assisted" | "autopilot";
  /** Normalized selected social channels; connection state is not planning eligibility. */
  selectedChannels: SocialMediaChannel[];
  planId: string | null;
  planGoal: string | null;
  planValidFrom: string | null;
  planValidUntil: string | null;
  /** Every `mara_drafts` id attached to the active plan, including rows the horizon filter hides. */
  planDraftIds: string[];
  items: WorkflowView[];
}

export const EMPTY_SNAPSHOT: WorkflowSnapshot = {
  timeZone: "Asia/Dubai", today: "", cadence: "3x_week", cadenceLabel: CADENCE_LABELS["3x_week"],
  mode: "assisted", selectedChannels: [], planId: null, planGoal: null, planValidFrom: null, planValidUntil: null, planDraftIds: [], items: [],
};

/** The new slot semantics: `source_plan_item_key` holds a real local date. */
const LOCAL_SLOT_DATE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * True when a draft uses the NEW date-based slot semantics — its per-plan slot
 * key is a real local YYYY-MM-DD date. Legacy ordinal keys ("0", "1", …) are
 * never current-workflow items, even when their publish time happens to fall
 * inside the live horizon.
 */
export function isLocalSlotDateKey(value: unknown): boolean {
  const key = String(value ?? "");
  if (!LOCAL_SLOT_DATE.test(key)) return false;
  const instant = Date.parse(`${key}T00:00:00Z`);
  // Round-trip guard: rejects impossible calendar dates the regex allows.
  return Number.isFinite(instant) && new Date(instant).toISOString().slice(0, 10) === key;
}

/** True when a draft carries a real, parseable proposed publish instant. */
export function isValidPublishInstant(value: unknown): boolean {
  return typeof value === "string" && value.length > 0 && Number.isFinite(Date.parse(value));
}

function pairForDraftRow(row: {
  kind?: unknown;
  social_channel?: unknown;
  social_format?: unknown;
  source_plan_item_key?: unknown;
}): { channel: SocialMediaChannel; format: SocialFormat } | null {
  const identity = parseWorkflowSlotIdentity(row.source_plan_item_key);
  // A composite source key is the immutable server assignment; never let
  // stale/conflicting columns make it appear as Instagram.
  if (identity?.channel && identity.format) return { channel: identity.channel, format: identity.format };
  if (isValidChannelFormat(row.social_channel, row.social_format)) {
    return { channel: row.social_channel as SocialMediaChannel, format: row.social_format as SocialFormat };
  }
  switch (row.kind) {
    case "instagram_post": return { channel: "instagram", format: "post" };
    case "reel": return { channel: "instagram", format: "reel" };
    case "story": return { channel: "instagram", format: "story" };
    case "tiktok_video": return { channel: "tiktok", format: "video" };
    case "youtube_short": return { channel: "youtube", format: "short" };
    case "youtube_video": return { channel: "youtube", format: "video" };
    default: return null;
  }
}

function nativeWorkflowStatus(draftStatus: string, queueStatus: string | null): WorkflowStatus {
  if (draftStatus === "rejected") return "failed";
  switch (queueStatus) {
    case "scheduled": return "scheduled";
    case "waiting_for_media": return "waiting_for_media";
    case "needs_declaration": return "needs_content";
    case "permission_required": return "failed";
    case "uploading":
    case "posting":
    case "provider_processing": return "publishing";
    case "published": return "published";
    case "failed": return "failed";
    case "cancelled": return draftStatus === "approved" ? "needs_content" : "planned";
    // Approval without a confirmed queue row is not a scheduled success. Keep
    // it actionable while the display label explains that sync was not proven.
    default: return draftStatus === "approved" ? "needs_content" : "planned";
  }
}

function socialQueueStatusLabel(
  channel: "tiktok" | "youtube",
  queue: { status: string; provider_privacy_status?: string | null } | { status: string } | null,
  draftStatus: string,
  publishAt: string,
): string {
  if (queue) {
    return channel === "youtube"
      ? youTubeQueueLabel(queue.status, "provider_privacy_status" in queue ? queue.provider_privacy_status ?? null : null)
      : tikTokQueueLabel(queue.status);
  }
  if (draftStatus === "rejected") return "Rejected";
  if (draftStatus === "approved") {
    return publishAt ? "Approved — queue sync not confirmed" : "Approved — add a schedule to queue publishing";
  }
  return "Draft — awaiting Social Studio approval";
}

/** What the horizon rule needs from one workflow view. */
export type CurrentWorkflowItem = Pick<WorkflowView, "slotDate" | "localDate" | "status">;

/**
 * The one validity rule for surfacing a workflow item in the CURRENT views.
 *
 * An item is part of the active rolling workflow when it already uses the new
 * date-based slot (guaranteed by the row-level pre-filter) AND either
 *   - its slot/local publish date lies inside the current rolling horizon
 *     `[today, today + horizonDays)` in the account timezone, or
 *   - it has progressed beyond planning — approved and scheduled, published,
 *     or missed/failed — so legitimate scheduled, published and NEEDS
 *     ATTENTION work stays visible wherever its date now sits.
 *
 * Deliberately NOT part of the rule: `created_at`. A valid date-keyed item
 * inside the current horizon is never hidden just because it was created
 * before this change (or long ago); stale items are hidden because their slot
 * is legacy or outside the horizon.
 */
export function isCurrentWorkflowItem(item: CurrentWorkflowItem, selection: { today: string; horizonDays?: number }): boolean {
  const horizonDays = selection.horizonDays ?? DEFAULT_HORIZON_DAYS;
  if (isWithinHorizon(selection.today, item.slotDate, horizonDays)) return true;
  if (item.localDate && isWithinHorizon(selection.today, item.localDate, horizonDays)) return true;
  // Waiting-for-media, delayed-media and timed-out-media items are LIVE
  // scheduled work whose visual is not ready yet: if the owner rescheduled
  // them beyond the horizon they must stay visible (a held schedule is never
  // silently hidden), exactly like scheduled/published/missed/failed work.
  return (
    item.status === "scheduled" || item.status === "published" || item.status === "missed" || item.status === "failed"
    || item.status === "waiting_for_media" || item.status === "media_delayed" || item.status === "media_timed_out"
  );
}

/**
 * Filters an approval-action list (the Approvals screen feed) so rolling-plan
 * workflow cards follow the same horizon rule as the rest of the read model.
 *
 * Only cards that belong to the active plan's drafts are filtered: a stale
 * `propose_calendar_item` card for a legacy/out-of-horizon plan draft never
 * appears as a current approval need. Everything else — other tool names,
 * chat proposals without a draft, cards for drafts outside the active plan —
 * is passed through untouched.
 */
export function filterApprovalActionsForCurrentWorkflow<
  T extends { id: string | number; tool_name: string; new_value?: Record<string, unknown> | null; sanitized_arguments?: Record<string, unknown> | null },
>(actions: T[], snapshot: Pick<WorkflowSnapshot, "items" | "planDraftIds">): T[] {
  const surfacedActionIds = new Set(
    snapshot.items.flatMap((item) => (item.approvalActionId ? [item.approvalActionId] : [])),
  );
  const planDraftIds = new Set(snapshot.planDraftIds.map(String));
  return actions.filter((action) => {
    if (action.tool_name !== "propose_calendar_item") return true;
    const args = (action.new_value ?? action.sanitized_arguments ?? null) as { sourceDraftId?: unknown } | null;
    const sourceDraftId = args?.sourceDraftId;
    // Not a rolling-plan workflow card: never hidden by the horizon filter.
    if (typeof sourceDraftId !== "string" || !planDraftIds.has(sourceDraftId)) return true;
    return surfacedActionIds.has(String(action.id));
  });
}

/**
 * Loads the ONE executable workflow snapshot for the ACTIVE rolling horizon.
 *
 * Scoped to the active plan and resolved in the account's business timezone.
 * Of the plan's drafts, only current-workflow items are surfaced (see
 * `isCurrentWorkflowItem`): new date-keyed slots inside the live horizon, plus
 * scheduled/published/missed/failed work. Legacy ordinal-slot rows and
 * out-of-horizon drafts stay in the database, untouched, and simply never
 * reach the current views.
 */
export async function loadWorkflowSnapshot(
  admin: AdminClient, ownerId: string, options: { now?: Date; horizonDays?: number } = {},
): Promise<WorkflowSnapshot> {
  const now = options.now ?? new Date();
  const { data: business } = await admin.from("businesses")
    .select("content_frequency,automation_level,timezone,plan,preferred_channels").eq("owner_user_id", ownerId).maybeSingle();
  const timeZone = accountTimezone((business as { timezone?: string | null } | null)?.timezone);
  const today = localDate(now, timeZone);
  const cadence = normalizeCadence(business?.content_frequency);
  
  const planId = normalizePlan((business as any)?.plan);
  let mode = business?.automation_level === "manual" || business?.automation_level === "autopilot"
    ? business.automation_level : "assisted";
  if (!canUseAutomationMode(planId, mode)) {
    mode = planId === "pro" ? "assisted" : "manual";
  }

  const { data: plan } = await admin.from("marketing_plans")
    .select("id,business_goal,valid_from,valid_until")
    .eq("owner_user_id", ownerId).eq("status", "active")
    .order("created_at", { ascending: false }).limit(1).maybeSingle();

  const snapshot: WorkflowSnapshot = {
    timeZone, today, cadence, cadenceLabel: CADENCE_LABELS[cadence], mode,
    selectedChannels: normalizeSelectedSocialChannels(business?.preferred_channels),
    planId: plan?.id ? String(plan.id) : null,
    planGoal: plan?.business_goal ? String(plan.business_goal) : null,
    planValidFrom: plan?.valid_from ? String(plan.valid_from) : null,
    planValidUntil: plan?.valid_until ? String(plan.valid_until) : null,
    planDraftIds: [],
    items: [],
  };
  if (!snapshot.planId) return snapshot;

  const { data: drafts } = await admin.from("mara_drafts")
    .select("id,kind,social_channel,social_format,title,content,content_meta,proposed_publish_at,status,source_plan_id,source_plan_item_key")
    .eq("owner_user_id", ownerId).eq("source_plan_id", snapshot.planId)
    .order("proposed_publish_at", { ascending: true });

  // History stays in the database: every active-plan draft id is kept on the
  // snapshot (so the Approvals feed can recognise stale plan cards), while the
  // surfaced items below are narrowed to the current rolling workflow.
  const allRows = drafts ?? [];
  snapshot.planDraftIds = allRows.map((row) => String(row.id));
  if (!allRows.length) return snapshot;

  // Date-only legacy Instagram identities and current date|channel_format
  // identities are both readable. Ordinal keys and unknown pairs stay hidden;
  // unknown rows are never silently mapped to Instagram.
  const rows = allRows.filter((row) =>
    parseWorkflowSlotIdentity(row.source_plan_item_key) !== null
      && isValidPublishInstant(row.proposed_publish_at)
      && pairForDraftRow(row) !== null,
  );
  if (!rows.length) return snapshot;

  const ids = rows.map((row) => String(row.id));
  const youtubeIds = rows.filter((row) => pairForDraftRow(row)?.channel === "youtube").map((row) => String(row.id));
  const tiktokIds = rows.filter((row) => pairForDraftRow(row)?.channel === "tiktok").map((row) => String(row.id));
  const [assets, generations, instagramQueue, calendar, approvals, productionActions, youtubeQueue, tiktokQueue] = await Promise.all([
    admin.from("post_draft_assets").select("draft_id,mime_type,origin,storage_path,display_name,status").eq("owner_user_id", ownerId).in("draft_id", ids),
    admin.from("mara_media_generations").select("draft_id,status,media_type,error_code,created_at,updated_at").eq("owner_user_id", ownerId).in("draft_id", ids).order("updated_at", { ascending: true }),
    admin.from("instagram_publish_queue").select("draft_id,status,instagram_media_id,failure_message,scheduled_at").eq("owner_user_id", ownerId).in("draft_id", ids),
    admin.from("content_calendar_items").select("id,source_draft_id").eq("owner_user_id", ownerId).in("source_draft_id", ids),
    admin.from("mara_pending_actions").select("id,sanitized_arguments,status")
      .eq("owner_user_id", ownerId).eq("tool_name", "propose_calendar_item").in("status", ["pending", "failed"]),
    admin.from("mara_pending_actions").select("id,new_value,sanitized_arguments,status,updated_at")
      .eq("owner_user_id", ownerId).eq("tool_name", "choose_reel_production").in("status", ["pending", "failed"])
      .order("updated_at", { ascending: true }),
    getYouTubeQueueItemsForDrafts(admin, ownerId, youtubeIds),
    getTikTokQueueItemsForDrafts(admin, ownerId, tiktokIds),
  ]);
  if (assets.error || generations.error || instagramQueue.error || calendar.error || approvals.error || productionActions.error) {
    throw new Error("workflow_snapshot_read_failed");
  }

  const assetRows = (assets.data ?? []) as Array<{ draft_id: string; mime_type: string | null; origin: string | null; storage_path: string | null; display_name: string | null; status: string | null }>;
  const assetByDraft = new Map<string, (typeof assetRows)[number]>(assetRows.map((row) => [String(row.draft_id), row]));
  const mediaByDraft = new Map<string, { status: string; mediaType: string | null; errorCode: string | null; createdAt: string | null; updatedAt: string | null }>();
  for (const row of generations.data ?? []) {
    // Rows arrive oldest-first, so the newest generation wins. The timing and
    // reason columns are kept: the read model derives "Media generation
    // delayed" from updated_at and "Generation timed out" from the video job's
    // lifetime (created_at) or its terminal provider_timeout reason.
    mediaByDraft.set(String(row.draft_id), {
      status: String(row.status),
      mediaType: typeof row.media_type === "string" ? row.media_type : null,
      errorCode: typeof row.error_code === "string" ? row.error_code : null,
      createdAt: typeof row.created_at === "string" ? row.created_at : null,
      updatedAt: typeof row.updated_at === "string" ? row.updated_at : null,
    });
  }
  const instagramQueueRows = (instagramQueue.data ?? []) as Array<{ draft_id: string; status: string; instagram_media_id: string | null; failure_message: string | null; scheduled_at: string | null }>;
  const publish = new Map<string, (typeof instagramQueueRows)[number]>(instagramQueueRows.map((row) => [String(row.draft_id), row]));
  const calendarRows = (calendar.data ?? []) as Array<{ id: string; source_draft_id: string }>;
  const calendarIds = new Map<string, string>(calendarRows.map((row) => [String(row.source_draft_id), String(row.id)]));
  const approvalIds = new Map<string, string>();
  for (const row of approvals.data ?? []) {
    const draftId = (row.sanitized_arguments as { sourceDraftId?: unknown } | null)?.sourceDraftId;
    if (typeof draftId === "string") approvalIds.set(draftId, String(row.id));
  }
  // The newest open reel-production action per draft carries its live state.
  interface ProductionActionRow { id: string; new_value?: Record<string, unknown> | null; sanitized_arguments?: Record<string, unknown> | null; status: string }
  const productionByDraft = new Map<string, ProductionActionRow>();
  for (const row of productionActions.data ?? []) {
    const value = (row.new_value ?? row.sanitized_arguments ?? null) as { draftId?: unknown } | null;
    const draftId = typeof value?.draftId === "string" ? value.draftId : null;
    if (draftId) productionByDraft.set(draftId, row);
  }

  snapshot.items = [];
  for (const row of rows) {
    const draftId = String(row.id);
    const identity = parseWorkflowSlotIdentity(row.source_plan_item_key)!;
    const pair = pairForDraftRow(row)!;
    const isInstagram = pair.channel === "instagram";
    const contentType: PlannedContentType = isInstagram
      ? pair.format as "post" | "reel" | "story"
      : pair.channel === "youtube" && pair.format === "short" ? "short" : "video";
    const publishAt = String(row.proposed_publish_at ?? "");
    const asset = assetByDraft.get(draftId) as { mime_type?: unknown; origin?: unknown; storage_path?: unknown; display_name?: unknown; status?: unknown } | undefined;
    const hasMedia = Boolean(asset && (asset.status === "uploaded" || typeof asset.storage_path === "string"));
    const media = mediaByDraft.get(draftId) ?? null;
    const youtubeRow = pair.channel === "youtube" ? youtubeQueue.get(draftId) ?? null : null;
    const tiktokRow = pair.channel === "tiktok" ? tiktokQueue.get(draftId) ?? null : null;
    const socialQueue = youtubeRow ?? tiktokRow;
    const instagramRow = isInstagram ? publish.get(draftId) as {
      status?: string;
      instagram_media_id?: string | null;
      failure_message?: string | null;
      scheduled_at?: string | null;
    } | undefined : undefined;
    const queueStatus = isInstagram
      ? (instagramRow?.status ?? null)
      : (socialQueue?.status ?? null);
    const draftStatus = String(row.status ?? "draft") as "draft" | "approved" | "rejected";
    const facts = {
      draftStatus,
      hasMedia,
      mediaStatus: (media?.status ?? null) as never,
      mediaUpdatedAt: media?.updatedAt ?? null,
      mediaCreatedAt: media?.createdAt ?? null,
      mediaErrorCode: media?.errorCode ?? null,
      mediaType: media?.mediaType ?? null,
      publishStatus: isInstagram ? (instagramRow?.status ?? null) : null,
      awaitingApproval: isInstagram && approvalIds.has(draftId),
      publishAt,
      now,
    };
    const status = isInstagram
      ? deriveWorkflowStatus(facts)
      : nativeWorkflowStatus(draftStatus, socialQueue?.status ?? null);

    let mediaPreviewUrl: string | null = null;
    // Only Instagram's media workflow uses the mara-media bucket. TikTok and
    // YouTube assets remain private in post_draft_assets and are represented by
    // safe metadata below; the provider queues receive them through their own
    // existing publisher path.
    if (isInstagram && hasMedia) {
      const { data: signed } = await admin.storage.from("mara-media")
        .createSignedUrl(String(asset!.storage_path), 600).catch(() => ({ data: null }) as { data: unknown });
      mediaPreviewUrl = (signed as { signedUrl?: string } | null)?.signedUrl ?? null;
    }

    const productionRow = productionByDraft.get(draftId) ?? null;
    const production = isInstagram && contentType === "reel" ? productionView(row, productionRow) : null;
    const contentMeta = row.content_meta && typeof row.content_meta === "object" && !Array.isArray(row.content_meta)
      ? row.content_meta as Record<string, unknown>
      : {};
    const nativeStatusLabel = isInstagram
      ? WORKFLOW_STATUS_LABELS[status]
      : socialQueueStatusLabel(pair.channel as "tiktok" | "youtube", socialQueue, draftStatus, publishAt);
    const failureMessage = isInstagram
      ? instagramRow?.failure_message ?? null
      : socialQueue?.failure_message ?? null;

    snapshot.items.push({
      draftId,
      calendarItemId: calendarIds.get(draftId) ?? null,
      slotDate: identity.date,
      channel: pair.channel,
      format: pair.format,
      channelLabel: SOCIAL_CHANNEL_LABELS[pair.channel],
      contentType,
      contentTypeLabel: isInstagram
        ? contentTypeLabel(contentType as "post" | "reel" | "story")
        : SOCIAL_FORMAT_LABELS[pair.channel][pair.format] ?? SOCIAL_CHANNEL_LABELS[pair.channel],
      sourceLabel: "Marketing Plan",
      sourcePlanId: String(row.source_plan_id ?? snapshot.planId),
      sourcePlanItemKey: String(row.source_plan_item_key),
      concept: String(row.title ?? ""),
      caption: String(row.content ?? ""),
      description: typeof contentMeta.description === "string" ? contentMeta.description : null,
      script: Array.isArray(contentMeta.script)
        ? contentMeta.script.filter((line): line is string => typeof line === "string")
        : [],
      publishAt,
      localDate: publishAt ? isoToLocalDate(publishAt, timeZone) : "",
      localTime: publishAt ? formatLocalTime(publishAt, timeZone) : "",
      dayLabel: publishAt ? relativeDayLabel(isoToLocalDate(publishAt, timeZone), now, timeZone) : "",
      status,
      statusLabel: nativeStatusLabel,
      failedStage: status === "failed"
        ? (draftStatus === "rejected" ? "rejected" : !isInstagram ? "publishing" : failureStage(facts))
        : failureStage(facts),
      failureMessage,
      missedReason: isInstagram ? missedReason(facts) : null,
      approvalActionId: isInstagram ? approvalIds.get(draftId) ?? null : null,
      hasMedia,
      instagramMediaId: isInstagram ? instagramRow?.instagram_media_id ?? null : null,
      mediaStatus: isInstagram ? media?.status ?? null : null,
      mediaPreviewUrl,
      mediaMimeType: hasMedia && typeof asset?.mime_type === "string" ? asset.mime_type : null,
      mediaDisplayName: hasMedia && typeof asset?.display_name === "string" ? asset.display_name : null,
      mediaFromMara: asset?.origin === "mara",
      queueStatus,
      production,
    });
  }
  // The horizon rule (see `isCurrentWorkflowItem`): the ACTIVE rolling horizon
  // in the account's business timezone, plus work that has already progressed
  // to scheduled/published or needs attention (missed/failed). Legacy and
  // out-of-horizon rows are simply left out of the current views; they remain
  // stored, untouched, for history.
  snapshot.items = snapshot.items.filter((item) => isCurrentWorkflowItem(item, { today, horizonDays: options.horizonDays }));
  return snapshot;
}

/**
 * Reel production facts for one plan item: the open `choose_reel_production`
 * action's resolved capability when one exists, otherwise derived on the fly
 * from the concept. Either way the Create-with-MARA option is RESOLVED —
 * recommended, adapted, or truthfully disabled with a reason.
 */
function productionView(
  row: Record<string, unknown>,
  actionRow: { id: string; new_value?: Record<string, unknown> | null; sanitized_arguments?: Record<string, unknown> | null; status: string } | null,
): WorkflowProductionView {
  const concept = String(row.title ?? "");
  const script = String(row.content ?? "");
  const value = (actionRow?.new_value ?? actionRow?.sanitized_arguments ?? null) as Record<string, unknown> | null;

  const capability = classifyReelProduction({ concept, script });
  const storedOption = value?.maraOption as MaraProductionOption | null | undefined;
  const maraOption = storedOption && typeof storedOption.state === "string" ? storedOption : capability.maraOption;
  const storedRecommended = typeof value?.recommendedMethod === "string" ? value.recommendedMethod as ReelProductionMethod : null;
  let availableMethods: ReelProductionMethod[] = Array.isArray(value?.availableMethods)
    ? (value!.availableMethods as unknown[]).filter((method): method is ReelProductionMethod =>
      typeof method === "string" && ["create_with_mara", "film_yourself", "upload_asset"].includes(method))
    : capability.availableMethods;
  // Older capability payloads hid Create with MARA whenever filming was
  // recommended. The recommended method and the available methods are
  // DIFFERENT concepts: as long as MARA has a safe equivalent (direct or
  // adapted), the option must stay visible.
  if (maraOption.state !== "unavailable" && !availableMethods.includes("create_with_mara")) {
    availableMethods = ["create_with_mara", ...availableMethods];
  }

  return {
    recommendedMethod: storedRecommended ?? capability.recommendedMethod,
    availableMethods,
    selectedMethod: typeof value?.selectedProductionMethod === "string" ? value.selectedProductionMethod as ReelProductionMethod : null,
    maraOption,
    actionId: actionRow?.id ?? null,
    productionStatus: typeof value?.productionStatus === "string" ? value.productionStatus : null,
    shotInstructions: Array.isArray(value?.shotInstructions)
      ? (value!.shotInstructions as unknown[]).filter((shot): shot is string => typeof shot === "string")
      : capability.shotInstructions,
    allowedAssetKinds: Array.isArray(value?.allowedAssetKinds)
      ? (value!.allowedAssetKinds as unknown[]).filter((kind): kind is "image" | "video" => kind === "image" || kind === "video")
      : capability.allowedAssetKinds,
    missingAssetRequest: typeof value?.missingAssetRequest === "string" ? value.missingAssetRequest : capability.missingAssetRequest,
    script: value && typeof value.script === "string" ? value.script : script,
  };
}

/** Items whose local publish date is the real current local date. */
export function itemsForToday(snapshot: WorkflowSnapshot): WorkflowView[] {
  return snapshot.items.filter((item) => item.localDate === snapshot.today);
}

/** Operational counts for the Today command centre. */
export function todaySummary(snapshot: WorkflowSnapshot) {
  const items = snapshot.items;
  return {
    publishingToday: itemsForToday(snapshot).filter((item) => item.status !== "failed" && item.status !== "missed"),
    needsApproval: items.filter((item) => item.status === "needs_approval"),
    generating: items.filter((item) => item.status === "generating"),
    // Scheduled but CANNOT publish until the visual is ready — surfaced as its
    // own truthful bucket, never folded into "Scheduled". A timed-out
    // generation belongs here too: the queue row is still held in
    // 'waiting_for_media', and the item's own label says "Generation timed out".
    waitingForMedia: items.filter((item) => item.status === "waiting_for_media" || item.status === "media_delayed" || item.status === "media_timed_out"),
    failed: items.filter((item) => item.status === "failed"),
    missed: items.filter((item) => item.status === "missed"),
    scheduled: items.filter((item) => item.status === "scheduled"),
    published: items.filter((item) => item.status === "published"),
    next: items.find((item) => item.status === "scheduled" || item.status === "publishing") ?? null,
  };
}
