import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import { AiError, createAiProvider } from "@/lib/ai";
import { evaluateAutopilotRecommendation } from "@/lib/mara/autopilot-safety";
import { composePostCaption } from "@/lib/post/core";
import { approvePostDraft, syncPostToCalendar, type AdminClient } from "@/lib/post/server-data";
import { CADENCE_LABELS, normalizeCadence, type Cadence } from "@/lib/voom/cadence";
import { accountTimezone, formatLocalTime, localDate } from "@/lib/voom/timezone";
import { ensureWorkflowMedia } from "./media";
import { buildPlannedContentPayload, plannedContentJsonSchema, plannedContentSchema, PLANNED_CONTENT_SYSTEM_PROMPT } from "./prompt";
import {
  ensureRollingPlan,
  type GeneratedContent,
  type PlanSlot,
  type RollingPlanPorts,
  type RollingPlanResult,
  type WorkflowItem,
  type WorkflowStage,
} from "./rolling-plan";
import { draftKindForContentType } from "./state";

/**
 * Wires the pure rolling-plan engine to Voom's existing production systems.
 *
 * Reused, never re-implemented:
 *   - marketing_plans          -> the plan header + rendered horizon,
 *   - mara_drafts              -> THE executable content item (one per slot),
 *   - mara_media_generations   -> MARA image/video generation,
 *   - mara_pending_actions     -> Approvals,
 *   - content_calendar_items   -> the visual schedule (mirror of the draft),
 *   - instagram_publish_queue  -> scheduled auto-publishing,
 *   - evaluateAutopilotRecommendation -> the one safety evaluator.
 */

export const WORKFLOW_CONVERSATION_TITLE = "Voom marketing workflow";

export interface WorkflowRunInput {
  ownerId: string;
  now?: Date;
  cadence?: Cadence;
  mode?: "manual" | "assisted" | "autopilot";
  /**
   * "planning_only" runs the same cadence-aware rolling planner and persists
   * the same drafts/plan items, but stops before `ensureMedia` and
   * `autoApproveAndSchedule`: no provider call, no media job, no approval, no
   * calendar scheduling, no queueing, no publishing. Defaults to "full".
   */
  stage?: WorkflowStage;
}

export async function runOwnerWorkflow(admin: AdminClient, input: WorkflowRunInput): Promise<RollingPlanResult> {
  const now = input.now ?? new Date();
  const { data: business } = await admin.from("businesses")
    .select("id,brand_name,brand_description,industry,target_customer,main_goal,brand_personality,preferred_channels,content_frequency,automation_level,timezone")
    .eq("owner_user_id", input.ownerId).maybeSingle();
  if (!business) throw new Error("business_not_found");

  const timeZone = accountTimezone((business as { timezone?: string | null }).timezone);
  const cadence = input.cadence ?? normalizeCadence(business.content_frequency);
  const mode = input.mode ?? normalizeMode(business.automation_level);
  const goal = String(business.main_goal ?? "Grow awareness");

  const ports = await buildWorkflowPorts(admin, {
    ownerId: input.ownerId,
    businessId: String(business.id),
    business,
    timeZone,
    cadence,
    goal,
    now,
  });
  return ensureRollingPlan(ports, { now, timeZone, cadence, mode, goal, stage: input.stage });
}

function normalizeMode(value: string | null | undefined): "manual" | "assisted" | "autopilot" {
  return value === "manual" || value === "autopilot" ? value : "assisted";
}

interface PortContext {
  ownerId: string;
  businessId: string;
  business: Record<string, unknown>;
  timeZone: string;
  cadence: Cadence;
  goal: string;
  now: Date;
}

export async function buildWorkflowPorts(admin: AdminClient, context: PortContext): Promise<RollingPlanPorts> {
  const conversationId = await ensureWorkflowConversation(admin, context.ownerId);
  const plannedConcepts: string[] = [];

  return {
    async ensurePlan({ validFrom, validUntil, cadence, goal }) {
      const { data: existing } = await admin.from("marketing_plans").select("id,valid_from,valid_until")
        .eq("owner_user_id", context.ownerId).eq("status", "active")
        .order("created_at", { ascending: false }).limit(1).maybeSingle();
      if (existing?.id) {
        await admin.from("marketing_plans")
          .update({ valid_from: validFrom, valid_until: validUntil, content_frequency: CADENCE_LABELS[cadence] })
          .eq("owner_user_id", context.ownerId).eq("id", existing.id);
        return String(existing.id);
      }
      const { data: created, error } = await admin.from("marketing_plans").insert({
        owner_user_id: context.ownerId,
        business_id: context.businessId,
        status: "active",
        business_goal: goal.slice(0, 1000) || "Grow awareness",
        weekly_strategy: `Rolling ${CADENCE_LABELS[cadence]} Instagram plan generated by Voom, starting ${validFrom}.`,
        selected_channels: ["Instagram"],
        content_frequency: CADENCE_LABELS[cadence],
        planned_posts: [],
        planned_campaigns: [],
        recommendations: [],
        source_summary: { engine: "rolling_plan_v2", timezone: context.timeZone },
        valid_from: validFrom,
        valid_until: validUntil,
      }).select("id").single();
      if (error || !created) throw new Error("plan_store_failed");
      return String(created.id);
    },

    async listItems(planId) {
      const { data } = await admin.from("mara_drafts")
        .select("id,kind,title,content,proposed_publish_at,status,source_plan_item_key")
        .eq("owner_user_id", context.ownerId).eq("source_plan_id", planId);
      const items = (data ?? []).map(toWorkflowItem);
      for (const item of items) plannedConcepts.push(item.concept);
      return items;
    },

    async generateContent(slot) {
      return generatePlannedContent({ context, slot, plannedConcepts });
    },

    async createDraft({ planId, slot, content }) {
      const caption = composePostCaption({ caption: content.caption, cta: content.cta, hashtags: content.hashtags });
      const row = {
        owner_user_id: context.ownerId,
        conversation_id: conversationId,
        source_plan_id: planId,
        source_plan_item_key: slot.date,
        kind: draftKindForContentType(slot.contentType),
        channel: slot.contentType === "reel" ? "Reel" : slot.contentType === "story" ? "Story" : "Instagram",
        title: content.concept.slice(0, 160),
        content: (caption || content.concept).slice(0, 12000),
        proposed_publish_at: slot.publishAt,
        status: "draft",
        media_brief: content.visualBrief.slice(0, 800),
      };
      // Idempotent on (owner, plan, slot date): a second cron run in the same
      // day reuses the existing item instead of creating a duplicate.
      const { data, error } = await admin.from("mara_drafts")
        .upsert(row, { onConflict: "owner_user_id,source_plan_id,source_plan_item_key", ignoreDuplicates: true })
        .select("id,kind,title,content,proposed_publish_at,status,source_plan_item_key").maybeSingle();
      if (error && error.code !== "23505") throw new Error("draft_create_failed");
      if (data) {
        plannedConcepts.push(content.concept);
        return toWorkflowItem(data);
      }
      const { data: existing } = await admin.from("mara_drafts")
        .select("id,kind,title,content,proposed_publish_at,status,source_plan_item_key")
        .eq("owner_user_id", context.ownerId).eq("source_plan_id", planId).eq("source_plan_item_key", slot.date).maybeSingle();
      if (!existing) throw new Error("draft_create_failed");
      return toWorkflowItem(existing);
    },

    async ensureMedia(item) {
      const { data: draft } = await admin.from("mara_drafts").select("media_brief")
        .eq("owner_user_id", context.ownerId).eq("id", item.draftId).maybeSingle();
      return ensureWorkflowMedia(admin, {
        ownerId: context.ownerId,
        draftId: item.draftId,
        conversationId,
        contentType: item.contentType,
        concept: item.concept,
        visualBrief: String(draft?.media_brief ?? item.concept),
      });
    },

    async requestApproval(item) {
      await ensureApprovalAction(admin, {
        ownerId: context.ownerId, conversationId, item, timeZone: context.timeZone,
      });
    },

    async autoApproveAndSchedule(item) {
      const safety = evaluateAutopilotRecommendation({
        title: item.concept, content: item.caption, publishAt: item.publishAt,
      }, context.now);
      if (!safety.safe) return { approved: false, reason: safety.blockers.join(",") };
      // Approval advances the SAME draft: it mirrors into the calendar and, if
      // the media is ready, into the existing Instagram publish queue.
      await approveWorkflowItem(admin, context.ownerId, item.draftId);
      await recordAutoApproval(admin, {
        ownerId: context.ownerId, conversationId, item, checks: safety.checks, timeZone: context.timeZone,
      });
      return { approved: true };
    },

    async savePlanItems(planId, items) {
      const plannedPosts = items.map((item) => ({
        draftId: item.draftId,
        slotDate: item.slotKey,
        contentType: item.contentType,
        title: item.concept,
        content: item.caption,
        channel: "Instagram",
        proposedPublishAt: item.publishAt,
      }));
      await admin.from("marketing_plans").update({ planned_posts: plannedPosts })
        .eq("owner_user_id", context.ownerId).eq("id", planId);
    },
  };
}

/** Approves a workflow draft and advances it into Scheduled. */
export async function approveWorkflowItem(admin: AdminClient, ownerId: string, draftId: string) {
  // approvePostDraft -> syncPostToCalendar -> syncPostToPublishQueue reuses the
  // existing calendar mirror and the existing Instagram publishing queue. No
  // new scheduler exists.
  const view = await approvePostDraft(admin, ownerId, draftId);
  if (!view) throw new Error("draft_not_found");
  return view;
}

/** Re-syncs an item after an edit without changing its approval state. */
export async function resyncWorkflowItem(admin: AdminClient, ownerId: string, draftId: string) {
  return syncPostToCalendar(admin, ownerId, draftId);
}

async function ensureWorkflowConversation(admin: AdminClient, ownerId: string): Promise<string> {
  const { data: existing } = await admin.from("mara_conversations").select("id")
    .eq("owner_user_id", ownerId).eq("title", WORKFLOW_CONVERSATION_TITLE).limit(1).maybeSingle();
  if (existing?.id) return String(existing.id);
  const { data, error } = await admin.from("mara_conversations")
    .insert({ owner_user_id: ownerId, title: WORKFLOW_CONVERSATION_TITLE }).select("id").single();
  if (error || !data) throw new Error("workflow_conversation_failed");
  return String(data.id);
}

/**
 * Opens the approval card for an item, if one is not already open. Approvals
 * therefore only ever contains items that genuinely still need a decision.
 */
async function ensureApprovalAction(
  admin: AdminClient,
  input: { ownerId: string; conversationId: string; item: WorkflowItem; timeZone: string },
): Promise<void> {
  const { item } = input;
  await ensureWorkflowApprovalCard(admin, input.ownerId, {
    draftId: item.draftId,
    conversationId: input.conversationId,
    concept: item.concept,
    caption: item.caption,
    publishAt: item.publishAt,
    contentType: item.contentType,
    timeZone: input.timeZone,
    approved: item.status === "approved",
  });
}

/**
 * Opens the approval card for one workflow item, if one is not already open.
 * Shared by the rolling workflow and the in-place Marketing Plan actions, so
 * "open a card" has exactly one implementation and re-running anything never
 * creates a second card (stable per-draft idempotency key).
 */
export async function ensureWorkflowApprovalCard(
  admin: AdminClient,
  ownerId: string,
  input: {
    draftId: string;
    conversationId: string;
    concept: string;
    caption: string;
    publishAt: string;
    contentType: "post" | "reel" | "story";
    timeZone: string;
    approved?: boolean;
    productionStatus?: string;
    statusNote?: string;
  },
): Promise<void> {
  const { data: open } = await admin.from("mara_pending_actions").select("id,new_value")
    .eq("owner_user_id", ownerId).eq("tool_name", "propose_calendar_item")
    .in("status", ["pending", "failed"]).contains("sanitized_arguments", { sourceDraftId: input.draftId })
    .limit(1).maybeSingle();
  if (open?.id) {
    // Record a production choice on the EXISTING card instead of a new one.
    if (input.productionStatus) {
      const value = (open.new_value ?? {}) as Record<string, unknown>;
      await admin.from("mara_pending_actions").update({
        new_value: { ...value, productionStatus: input.productionStatus },
        result_summary: input.statusNote ?? "Production choice recorded.",
      }).eq("id", String(open.id)).eq("owner_user_id", ownerId);
    }
    return;
  }
  if (input.approved) return;
  const item = {
    draftId: input.draftId,
    concept: input.concept,
    caption: input.caption,
    publishAt: input.publishAt,
    contentType: input.contentType,
  };

  const args = {
    title: item.concept,
    channel: item.contentType === "reel" ? "Reel" : item.contentType === "story" ? "Story" : "Instagram",
    content: item.caption,
    topic: item.concept,
    publishAt: item.publishAt,
    sourceDraftId: item.draftId,
    reason: "Part of your rolling Voom content plan.",
  };
  await admin.from("mara_pending_actions").insert({
    owner_user_id: ownerId,
    conversation_id: input.conversationId,
    tool_name: "propose_calendar_item",
    sanitized_arguments: args,
    summary: `Approve “${item.concept}” for ${formatLocalTime(item.publishAt, input.timeZone)} on ${localDate(new Date(item.publishAt), input.timeZone)}.`,
    new_value: input.productionStatus ? { ...args, productionStatus: input.productionStatus } : args,
    // Stable per-draft key: re-running the plan never creates a second card.
    idempotency_key: `workflow-approval:${item.draftId}`,
  });
}

/** Records the Autopilot auto-approval in the existing audit trail. */
async function recordAutoApproval(
  admin: AdminClient,
  input: { ownerId: string; conversationId: string; item: WorkflowItem; checks: string[]; timeZone: string },
): Promise<void> {
  const summary = `Auto-approved by Autopilot after deterministic safety checks and scheduled for ${formatLocalTime(input.item.publishAt, input.timeZone)}.`;
  await admin.from("mara_tool_runs").insert({
    owner_user_id: input.ownerId,
    conversation_id: input.conversationId,
    tool_name: "propose_calendar_item",
    sanitized_arguments: {
      sourceDraftId: input.item.draftId,
      autopilotApproval: { automatic: true, mode: "autopilot", deterministicSafetyChecks: "passed", checks: input.checks },
    },
    status: "succeeded",
    idempotency_key: `workflow-autopilot:${input.item.draftId}`,
    result_summary: summary.slice(0, 1000),
    completed_at: new Date().toISOString(),
  });
  // Any approval card that was previously opened for this item is resolved, so
  // safely auto-approved content never sits in Approvals.
  await admin.from("mara_pending_actions")
    .update({ status: "confirmed", result_summary: summary.slice(0, 1000), executed_at: new Date().toISOString() })
    .eq("owner_user_id", input.ownerId).eq("tool_name", "propose_calendar_item")
    .in("status", ["pending", "failed"]).contains("sanitized_arguments", { sourceDraftId: input.item.draftId });
}

async function generatePlannedContent(
  input: { context: PortContext; slot: PlanSlot; plannedConcepts: string[] },
): Promise<GeneratedContent> {
  const { context, slot } = input;
  const business = context.business;
  const payload = buildPlannedContentPayload({
    business: {
      name: String(business.brand_name ?? "Your business"),
      description: String(business.brand_description ?? "").slice(0, 800),
      industry: String(business.industry ?? ""),
      targetCustomer: arrayText(business.target_customer),
      mainGoal: String(business.main_goal ?? ""),
      brandPersonality: arrayText(business.brand_personality),
    },
    goal: context.goal,
    cadenceLabel: CADENCE_LABELS[context.cadence],
    contentType: slot.contentType,
    localDate: slot.date,
    localTime: formatLocalTime(slot.publishAt, context.timeZone),
    timezone: context.timeZone,
    recentConcepts: input.plannedConcepts,
  });
  try {
    const plan = await createAiProvider().structured({
      messages: [
        { role: "system", content: PLANNED_CONTENT_SYSTEM_PROMPT },
        { role: "user", content: JSON.stringify(payload) },
      ],
      temperature: 0.7,
      maxTokens: 1200,
      jsonSchema: plannedContentJsonSchema,
      parse: (value) => plannedContentSchema.parse(value),
    });
    return {
      concept: plan.concept,
      caption: plan.caption,
      cta: plan.cta,
      hashtags: slot.contentType === "story" ? [] : plan.hashtags,
      visualBrief: plan.visualBrief,
    };
  } catch (reason) {
    if (reason instanceof AiError && reason.code === "rate_limited") throw new Error("content_rate_limited");
    throw new Error("content_generation_failed");
  }
}

function toWorkflowItem(row: Record<string, unknown>): WorkflowItem {
  const kind = String(row.kind ?? "instagram_post");
  return {
    draftId: String(row.id),
    slotKey: String(row.source_plan_item_key ?? ""),
    contentType: kind === "reel" ? "reel" : kind === "story" ? "story" : "post",
    concept: String(row.title ?? ""),
    caption: String(row.content ?? ""),
    publishAt: String(row.proposed_publish_at ?? ""),
    status: String(row.status ?? "draft"),
  };
}

function arrayText(value: unknown): string {
  return Array.isArray(value) ? value.map(String).join(", ") : String(value ?? "");
}

export type { RollingPlanResult, WorkflowStage };
export type WorkflowAdmin = SupabaseClient;
