"use client";

import Link from "next/link";
import { useState } from "react";
import { Icon } from "@/components/voom/icons";
import { Btn, Card, Tag } from "@/components/voom/ui/primitives";

interface PlanRecord { id: string; business_goal: string; weekly_strategy: string; selected_channels: string[]; content_frequency: string; planned_posts: Array<Record<string, unknown>>; planned_campaigns: Array<Record<string, unknown>>; recommendations: Array<Record<string, unknown>>; valid_from: string; valid_until: string; created_at: string; }

export function PlanWorkspace({ initial, storageReady }: { initial: PlanRecord | null; storageReady: boolean }) {
  const [plan, setPlan] = useState(initial); const [ready, setReady] = useState(storageReady); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [approvalReady, setApprovalReady] = useState(false);
  async function generate() { setBusy(true); setError(""); setApprovalReady(false); const response = await fetch("/api/plan", { method: "POST" }); const body = await response.json() as { plan?: PlanRecord; workflow?: { pendingActionIds: string[] }; error?: string }; if (response.ok && body.plan && body.workflow?.pendingActionIds.length === 3) { setPlan(body.plan); setReady(true); setApprovalReady(true); window.dispatchEvent(new Event("voom:data-changed")); } else setError(body.error ?? "Voom couldn't build your plan right now."); setBusy(false); }
  if (!plan) return <Card className="p-7 text-center sm:p-10"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[var(--brand-soft)] text-brand"><Icon name="spark" size={24} /></span><h2 className="mt-4 font-display text-xl font-semibold">Build your first marketing plan</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-text-2">Voom will use your saved brand, goals, audience, channels, calendar, campaigns, and recent performance. The result is saved as a plan—not a chat message.</p>{!ready && <p className="mx-auto mt-3 max-w-xl rounded-xl border border-amber/30 bg-amber/10 px-4 py-3 text-xs text-amber">The secure plan migration is prepared locally and must be approved before plan generation can be enabled.</p>}{error && <p role="alert" className="mt-3 text-sm text-red">{error}</p>}<Btn className="mt-5" variant="primary" disabled={busy || !ready} onClick={() => void generate()}><Icon name="spark" size={15} />{busy ? "Building your plan…" : "Generate plan"}</Btn></Card>;
  return <div>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-line bg-surface px-4 py-3"><div><span className="text-xs text-text-3">Active plan · {plan.valid_from} to {plan.valid_until}</span><p className="mt-0.5 text-sm font-semibold">{plan.content_frequency}</p></div><Btn variant="outline" size="sm" disabled={busy} onClick={() => void generate()}><Icon name="spark" size={14} />{busy ? "Refreshing…" : "Refresh plan"}</Btn></div>
    {approvalReady && <div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber/35 bg-amber/10 px-4 py-3"><p className="text-sm"><b>Your 3 Instagram recommendations are ready.</b> Review and approve each one independently.</p><Link href="/app/approvals" className="text-sm font-semibold text-brand hover:underline">Open Approvals →</Link></div>}
    {error && <p role="alert" className="mb-4 rounded-xl border border-red/35 bg-red/10 px-4 py-3 text-sm text-red">{error}</p>}
    <Card className="p-5 sm:p-6"><span className="text-xs font-bold uppercase tracking-[.08em] text-brand">Business goal</span><h2 className="mt-2 font-display text-xl font-semibold">{plan.business_goal}</h2><p className="mt-3 max-w-4xl text-sm leading-relaxed text-text-2">{plan.weekly_strategy}</p><div className="mt-4 flex flex-wrap gap-2">{plan.selected_channels.map((channel) => <Tag key={channel} tone="t-brand">{channel}</Tag>)}</div></Card>
    <section className="mt-5"><h2 className="mb-3 font-display text-lg font-semibold">Weekly content</h2>{plan.planned_posts.length ? <Card className="overflow-hidden">{plan.planned_posts.map((post, index) => <div key={`${post.proposedPublishAt}-${index}`} className="grid gap-3 border-t border-line px-4 py-4 first:border-0 md:grid-cols-[160px_110px_1fr]"><div className="text-sm font-semibold">{new Date(String(post.proposedPublishAt ?? "")).toLocaleString("en-AE", { timeZone: "Asia/Dubai", weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</div><Tag tone="t-grey" className="self-start justify-self-start">{String(post.channel ?? "Channel")}</Tag><div><b className="text-sm">{String(post.title ?? post.topic ?? "Content idea")}</b><p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed text-text-2">{String(post.content ?? "")}</p><p className="mt-2 text-xs text-text-3"><b>Why:</b> {String(post.recommendationReason ?? "")}</p></div></div>)}</Card> : <Empty text="No posts were recommended for this plan." />}</section>
    <section className="mt-5"><h2 className="mb-3 font-display text-lg font-semibold">Campaigns</h2>{plan.planned_campaigns.length ? <div className="grid gap-3 lg:grid-cols-2">{plan.planned_campaigns.map((campaign, index) => <Card key={`${campaign.name}-${index}`} className="p-4"><div className="flex items-start justify-between gap-2"><b>{String(campaign.name ?? "Campaign")}</b><Tag>{String(campaign.channel ?? "Channel")}</Tag></div><p className="mt-2 text-sm text-text-2">{String(campaign.objective ?? "")}</p><p className="mt-2 text-xs text-text-3">{String(campaign.schedule ?? "")}</p><ul className="mt-3 space-y-1.5 text-sm">{Array.isArray(campaign.actions) && campaign.actions.map((action, i) => <li key={i} className="flex gap-2"><span className="text-brand">•</span>{String(action)}</li>)}</ul><p className="mt-3 text-xs text-text-3"><b>Why:</b> {String(campaign.recommendationReason ?? "")}</p></Card>)}</div> : <Empty text="No campaign work was recommended for this plan." />}</section>
    <section className="mt-5"><h2 className="mb-3 font-display text-lg font-semibold">Recommendations</h2><Card className="overflow-hidden">{plan.recommendations.map((recommendation, index) => <div key={`${recommendation.title}-${index}`} className="border-t border-line px-4 py-4 first:border-0"><div className="flex flex-wrap items-start justify-between gap-2"><b className="text-sm">{String(recommendation.title ?? "Recommendation")}</b><div className="flex gap-2"><Tag>{String(recommendation.channel ?? "Voom")}</Tag>{recommendation.needsApproval === true && <Tag tone="t-amber">Approval required</Tag>}</div></div><p className="mt-1 text-sm text-text-2">{String(recommendation.action ?? "")}</p><p className="mt-2 text-xs text-text-3"><b>Why:</b> {String(recommendation.why ?? "")}</p></div>)}</Card></section>
  </div>;
}
function Empty({ text }: { text: string }) { return <Card className="p-6 text-center text-sm text-text-3">{text}</Card>; }
