import { PageHead } from "@/components/voom/shell/AppShell";
import { Card, Tag } from "@/components/voom/ui/primitives";
import { AutomationMode } from "@/components/voom/operating/AutomationMode";
import { normalizeAutomationMode } from "@/lib/voom/automation";
import { getOperatingData } from "@/lib/voom/operating-data";

export const dynamic = "force-dynamic";
export default async function AutomationsPage() { const data = await getOperatingData(); if (!data) return null; return <div><PageHead title="Automations" description="Choose how proactively Voom prepares your marketing." /><Card className="p-5 sm:p-6"><h2 className="font-display text-lg font-semibold">Automation mode</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-text-2">Assisted is the default: Voom plans and drafts proactively, then asks before protected changes.</p><div className="mt-4 max-w-md"><AutomationMode initial={normalizeAutomationMode(data.business.automation_level)} /></div><div className="mt-6 grid gap-3 md:grid-cols-3"><Mode title="Manual" text="Voom waits for you to request planning or drafting." /><Mode title="Assisted" text="Voom prepares plans, drafts, and recommendations, then asks for decisions." active /><Mode title="Autopilot" text="Voom can prepare and schedule approved internal work more proactively." /></div></Card><Card className="mt-4 p-5"><div className="flex items-start gap-3"><Tag tone="t-green">Safety always on</Tag><p className="text-sm leading-relaxed text-text-2">No mode can publish externally, send a campaign, delete content, or spend advertising money without a separately saved permission or an explicit confirmation.</p></div></Card></div>; }
function Mode({ title, text, active }: { title: string; text: string; active?: boolean }) { return <div className={`rounded-xl border p-4 ${active ? "border-brand bg-[var(--brand-soft)]" : "border-line bg-surface-2"}`}><b>{title}{active ? " · Default" : ""}</b><p className="mt-1 text-xs leading-relaxed text-text-3">{text}</p></div>; }
